### ISSUE TITLE
Review by team 45 - Helliums

### ISSUE THREAD

**Issue by Oitur** [SantiagoGuerra/tic-tac-toe#3]
Hey Maria/Santiago!

Good work so far! Here are some recommendations for your project:

- Start thinking on the way the input from the users is going to interact with the classes that you are actually going to use in the game.
- Try using %( ) instead of drawing with puts statements line by line
- Keep your code DRY, for instance, when asking for player's names you can use "2.times do"

Keep up the good work! Happy coding!

**Comment by euqueme** [comment]
Thank you for all the advice we kept it as dry as possible! and we haven't used multiple prints so far but we'll take it into count.
