### ISSUE TITLE
review 2 - team 45 Helliums

### ISSUE THREAD

**Issue by Oitur** [SantiagoGuerra/tic-tac-toe#4]
Good work so far Maria and Santiago!

As discussed in the morning session, the code shows that it still needs some work. I'm just giving a general recommendation:

Try to make classes independent from each other as much as possible. If classes depend on each other, as code grows, it's more difficult to debug, should something go wrong. For this particular project, you're not going to find difficulties, as it is a small project, however, if the project grows, it gets harder to identify and correct bugs if your classes are not independent.

**Comment by euqueme** [comment]
Thank you for this advice, we actually follow it so now you can see the only class that has all the dependencies is the Game class.
