### ISSUE TITLE
Code review - team 45 Helliums

### ISSUE THREAD

**Issue by Oitur** [SantiagoGuerra/tic-tac-toe#7]
Hello Santiago, Maria:

So, we saw that in your pull request there is a bug when trying to choose X or O, so I have a few suggestions:

Use gets.chomp.upcase to get your input, this way it will take x or X as valid input.
Use default values, so that it will be ok for the players to just hit enter and still play.
When somebody wins sometimes the output is "you win" and then "nobody wins"

It is looking good so far, but do try to make your user input what you want them to input, not just anything that comes their way.

**Comment by euqueme** [comment]
Thank you very much for your review we fix everything and submitted a pull request with the suggested changes.
